### ISSUE TITLE
Ability to auto-start queued chapter downloads

### ISSUE THREAD

**Issue by wopian** [CheviOne/Aizoban#10]
It's fairly annoying to have to constantly go to the queue and open the context menu to begin downloading queued chapters every time. (If they even download #5)

I.E a minimum of 3 taps is required to download a single chapter, while most other decent manga apps are able to do it in 1 tap. (MangaWatcher/Manga Rock)

**Comment by CheviOne** [comment]
Good suggestion, I will take a look at that.
