### ISSUE TITLE
Search into multiple catalog

### ISSUE THREAD

**Issue by Kcchouette** [CheviOne/Aizoban#16]
Can you add the possibility to search a manga in more than one catalog (for example to search "One Piece" on EN catalog -MangaHere, MangaFox, Batoto)?

The first goal is when we search a manga that a catalog has not, the other can have it.

Thanks

**Comment by Syborg49** [comment]
Like how mangawatcher does?

**Comment by Kcchouette** [comment]
I don't know how mangawatcher works

**Comment by Syborg49** [comment]
Mangawatcher works exactly how you described it. It searches all of its catalogues for what you searched for.  That'd be a great addition to Aizōban in my opinion.

**Comment by Kcchouette** [comment]
It's https://bitbucket.org/_vadia/manga-watcher-public/ ?

**Comment by wopian** [comment]
@Kcchouette it is that repository. :smile:
