### ISSUE TITLE
Adding Fork Changes to Master Branch

### ISSUE THREAD

**Issue by IpodHero188** [CheviOne/Aizoban#22]
@CheviOne  I wanted to see if you could add my fast scrolling on the chapter download list page change to the repository. I already have the change done and tested for awhile off a fork of your code, but I didn't know how I could get you to add it to your master branch of the code. 

The only thing is that the scrollbar's color needs to be uniformed with the color of the rest of the app, but the functionality works perfectly.

**Comment by paolobueno** [comment]
The standard way is to make a [pull request](https://help.github.com/articles/using-pull-requests/). It would be nice if you cleaned your repository a bit, since you've (maybe accidentally) added files that aren't supposed to be tracked such as `*.iml`, `.idea/` and even your generated `.apk`s to your repo.

**Comment by IpodHero188** [comment]
@paolobueno Thanks for the help. The reason for the APK is due to the fact that there was a group of people that wanted my change, so I added the APK file to the root for them. Before that, it was only going to be for me. 

I will update my git ignore file to exclude those files, however, since several from that group are still downloading my latest version, I will probably leave the APK until @CheviOne adds in the change.

**Comment by paolobueno** [comment]
Oh, you can use the [releases](https://help.github.com/articles/creating-releases/) mechanism and `git tag` to do that, then you can keep your repo clean :)

**Comment by CheviOne** [comment]
Done. ^^
