### ISSUE TITLE
Extremely slow download

### ISSUE THREAD

**Issue by lc-guy** [CheviOne/Aizoban#5]
It just says "pending" or "fetching links".

Anyway, do you have any nice resource for learning java development? I'd really like to contribute to this.

**Comment by CheviOne** [comment]
Hi, thank you for this information but unfortunately I couldn't reproduce your problem with Batoto. Maybe it was temporarily unavailable and just keep in mind that Batoto is sometimes realy slow.
Let me know if this problem consist for you.

**Comment by wopian** [comment]
This is also happening for me with Batato and MangaEden manga.

**Comment by lc-guy** [comment]
yeah, that's what's happening too for me.

**Comment by CheviOne** [comment]
Could you please give me some more information about your internet connection. I suspect that low network speed could cause timeout error, if too many simultaneous connections persist.

**Comment by wopian** [comment]
At the time 30 mbps download. Sometimes it stays stuck on "Failed" other times that message briefly flashes up and stays as "Fetching".

For reference, Mangawatcher downloaded 200 new chapters in under 30 minutes from Batoto sources yesterday with similar network speeds.

**Comment by lc-guy** [comment]
7.52 mbps here. Same as above: Mangawatcher downloads really fast from batoto, mangahere, or any other source.

**Comment by wopian** [comment]
Benchmark:

Manga: +Anima
Source: Batoto
Test 1: Single chapter; Chapter 1 (51 pages)
Test 2: Multiple chapters; Chapter 2, 3, 4, 5 & 6

Test | MangaWatcher | Aizoban
--- | --- | ---
1 | 01:41s | 01:51s
2 | 06:44 | Still running 70 minutes in with 4 on fetching and 1 on pending

**Comment by CheviOne** [comment]
I try to fix this next week. Hopefully we get rid of the problem ^^

**Comment by wopian** [comment]
Oh Batoto went live with members-only recently. Neither Aizoban or Manga watched are able to scrape :/

http://bato.to/forums/topic/23683-batoto-becoming-registered-only/

**Comment by digiwombat** [comment]
MangaDLR has a solution but he keeps his source closed.

**Comment by Ligerx** [comment]
Regarding batoto, I believe that they will still allow apps to use their website, the only restriction is that users must log in first.
I think mangarock handled the batoto issue.
You can also look at [this other manga reader project](https://github.com/inorichi/mangafeed) who has it working.
